# Generated by Django 3.2.6 on 2022-05-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotas',
            name='numbre_de_la_cuotas',
            field=models.CharField(default=None, max_length=50, verbose_name='numbre_de_la_cuotas'),
        ),
    ]
