# Generated by Django 3.2.6 on 2022-05-21 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_del_grupo', models.CharField(max_length=50, verbose_name='Nombre_del_grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=50, verbose_name='nombre_de_la_actividad')),
                ('descripción', models.CharField(max_length=50, verbose_name='nombre_de_la_descripción')),
                ('duración', models.DurationField(help_text='duración del evento')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.grupo', verbose_name='La clase grupal debe pertenecer a')),
            ],
        ),
    ]
