# Generated by Django 3.2.6 on 2022-05-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='nombre_de_la_habitacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
