# Generated by Django 3.2.6 on 2022-05-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='imagenes/clientes/')),
                ('tipo_cliente', models.CharField(choices=[('S', 'SOCIO'), ('V', 'VISITA')], max_length=8)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('direccion', models.CharField(max_length=200)),
                ('cuota', models.FloatField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=80)),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=9)),
                ('rol', models.CharField(choices=[('1', 'ROL1'), ('2', 'ROL2')], max_length=8)),
            ],
        ),
    ]
