# Generated by Django 3.2.6 on 2022-05-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
